[package]
name = "put-config-program"
description = "PUT Config program"
documentation = "https://docs.rs/put-config-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
chrono = { workspace = true, features = ["default", "serde"] }
serde = { workspace = true }
serde_derive = { workspace = true }
put-program-runtime = { workspace = true }
put-sdk = { workspace = true }

[dev-dependencies]
put-logger = { workspace = true }

[lib]
crate-type = ["lib"]
name = "put_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
