[package]
name = "put-bpf-loader-program"
description = "PUT BPF loader"
documentation = "https://docs.rs/put-bpf-loader-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
byteorder = { workspace = true }
libsecp256k1 = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
put-measure = { workspace = true }
put-program-runtime = { workspace = true }
put-sdk = { workspace = true }
put-zk-token-sdk = { workspace = true }
put_rbpf = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
memoffset = { workspace = true }

[lib]
crate-type = ["lib"]
name = "put_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
