[package]
name = "put-stake-program"
description = "PUT Stake program"
documentation = "https://docs.rs/put-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
put-config-program = { workspace = true }
put-program-runtime = { workspace = true }
put-sdk = { workspace = true }
put-vote-program = { workspace = true }
ethnum = { workspace = true }


[dev-dependencies]
assert_matches = { workspace = true }
proptest = { workspace = true }
put-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "put_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
