[package]
name = "put-rpc-client-api"
description = "Put Client Common Utilities"
documentation = "https://docs.rs/put-rpc-client-api"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bs58 = { workspace = true }
jsonrpc-core = { workspace = true, features = ["arbitrary_precision"] }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
semver = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
put-account-decoder = { workspace = true }
put-sdk = { workspace = true }
put-transaction-status = { workspace = true }
put-version = { workspace = true }
ppl-token = { workspace = true, features = ["no-entrypoint"] }
thiserror = { workspace = true }

[dev-dependencies]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
