[package]
name = "put-transaction-dos"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
put-clap-utils = { workspace = true }
put-cli = { workspace = true }
put-client = { workspace = true }
put-core = { workspace = true }
put-faucet = { workspace = true }
put-gossip = { workspace = true }
put-logger = { workspace = true }
put-measure = { workspace = true }
put-net-utils = { workspace = true }
put-rpc-client = { workspace = true }
put-runtime = { workspace = true }
put-sdk = { workspace = true }
put-streamer = { workspace = true }
put-transaction-status = { workspace = true }
put-version = { workspace = true }

[dev-dependencies]
put-local-cluster = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
