[package]
name = "put-banks-server"
description = "PUT banks server"
documentation = "https://docs.rs/put-banks-server"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
futures = { workspace = true }
put-banks-interface = { workspace = true }
put-client = { workspace = true }
put-runtime = { workspace = true }
put-sdk = { workspace = true }
put-send-transaction-service = { workspace = true }
tarpc = { workspace = true, features = ["full"] }
tokio = { workspace = true, features = ["full"] }
tokio-serde = { workspace = true, features = ["bincode"] }

[lib]
crate-type = ["lib"]
name = "put_banks_server"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
