[package]
name = "put-compute-budget-program"
description = "PUT Compute Budget program"
documentation = "https://docs.rs/put-compute-budget-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
put-program-runtime = { workspace = true }
put-sdk = { workspace = true }

[lib]
crate-type = ["lib"]
name = "put_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
