# This package only exists to avoid circular dependencies during cargo publish:
# put-bpf-loader-program -> put-program-test -> put-bpf-loader-program

[package]
name = "put-bpf-loader-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
put-bpf-loader-program = { workspace = true }
put-program-test = { workspace = true }
put-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
