[package]
name = "put-sbf-rust-upgraded"
documentation = "https://docs.rs/put-sbf-rust-upgraded"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
put-program = { workspace = true }

[lib]
name = "put_sbf_rust_upgraded"
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
