[package]
name = "put-test-validator"
description = "Blockchain, Rebuilt for Scale"
readme = "../README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
put-cli-output = { workspace = true }
put-client = { workspace = true }
put-core = { workspace = true }
put-geyser-plugin-manager = { workspace = true }
put-gossip = { workspace = true }
put-ledger = { workspace = true }
put-logger = { workspace = true }
put-net-utils = { workspace = true }
put-program-runtime = { workspace = true }
put-program-test = { workspace = true }
put-rpc = { workspace = true }
put-rpc-client = { workspace = true }
put-runtime = { workspace = true }
put-sdk = { workspace = true }
put-streamer = { workspace = true }
put-tpu-client = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
