[package]
name = "put-send-transaction-service"
description = "PUT send transaction service"
documentation = "https://docs.rs/put-send-transaction-service"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
log = { workspace = true }
put-client = { workspace = true }
put-measure = { workspace = true }
put-metrics = { workspace = true }
put-runtime = { workspace = true }
put-sdk = { workspace = true }
put-tpu-client = { workspace = true }

[dev-dependencies]
put-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
