[package]
name = "put-storage-hbase"
description = "PUT Storage HBase"
documentation = "https://docs.rs/put-storage-hbase"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
thrift = "0.17.0"
thiserror = { workspace = true }
backoff = { workspace = true, features = ["tokio"] }
bincode = { workspace = true }
bzip2 = { workspace = true }
enum-iterator = { workspace = true }
flate2 = { workspace = true }
zstd = { workspace = true }
log = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
put-metrics = { workspace = true }
put-sdk = { workspace = true }
put-storage-proto = { workspace = true }
put-transaction-status = { workspace = true }



[lib]
crate-type = ["lib"]
name = "put_storage_hbase"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
