[package]
name = "put-vote-program"
description = "PUT Vote program"
documentation = "https://docs.rs/put-vote-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
put-frozen-abi = { workspace = true }
put-frozen-abi-macro = { workspace = true }
put-metrics = { workspace = true }
put-program = { workspace = true }
put-program-runtime = { workspace = true }
put-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
put-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "put_vote_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
